### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by joostkuif** [tenderlove/esp8266aq#1]
Hi Aaron, i saw your PCB on twitter. Could you please publish/open source this too? would be great!

Joost

**Comment by tenderlove** [comment]
Hi!

Thanks for filing this.  I finally got some time today and pushed the schematic and PCBs.  I've also checked in a zipfile of the gerber files so you can just upload that to whatever PCB place you like.  The gerbers are [here](https://github.com/tenderlove/esp8266aq/blob/master/pcb/gerbers.zip).

I'm working on a parts list now and I'll put that in the readme
