### ISSUE TITLE
ESP connector 6 or 8?

### ISSUE THREAD

**Issue by joostkuif** [tenderlove/esp8266aq#4]
Hi Aaron,

On the parts list you have specified 6 pins for the connector. The PCB and the ESP have 8. On the picture of your resulting board I can't figure out how it is connected. Can you shine your light on this?

Thanks man!
Joost

**Comment by tenderlove** [comment]
@joostkuif ah, sorry.  This is a mistake.  I meant an 8pin connector.  I'll update the documentation.

**Comment by joostkuif** [comment]
Ow man, did you fell of a statue! 😜
