### ISSUE TITLE
ESP-01

### ISSUE THREAD

**Issue by unlimit** [tenderlove/esp8266aq#8]
Hi Aaron,

In Jan 2021 I first time saw this project and really liked it! Then in February I bought all the necessary parts. Unfortunately I didn't have time to assemble it until now.  But now I see that ESP-01 chip was replaced with ESP-12F. I have parts for 4 devices and have doubts which way to go:
- order ESP-12F chips 
- assemble devices by outdated circuit with ESP-01.  

Could you please explain the advantages of ESP-12F vs ESP-01 for this project?
Thank you!

Abliamit.

**Comment by tenderlove** [comment]
@unlimit The ESP-01 doesn't have as many GPIO pins exposed so I don't think there are as many features.  If you build the ESP-01 version you'll need a separate programmer module, where the ESP-12F can be programmed in-place.

Hope that helps!
